// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bg-animations/GradeMagnetica.tsx": () => import("../components/mockups/bg-animations/GradeMagnetica.tsx"),
  "./components/mockups/bg-animations/Nebulosa.tsx": () => import("../components/mockups/bg-animations/Nebulosa.tsx"),
  "./components/mockups/bg-animations/Particulas.tsx": () => import("../components/mockups/bg-animations/Particulas.tsx")
};
